services:
  portainer:
    container_name: portainer
    image: portainer/portainer-ee:latest
    ports:
      - 9443:9443
      - 8000:8000
    volumes:
        - ${PORTAINER_DATA}:/data
        - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped