---
services:
  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Warsaw
      - TRANSMISSION_WEB_HOME= #optional
      - USER=${USERNAME} #optional
      - PASS=${PASSWORD} #optional
      - WHITELIST= #optional
      - PEERPORT= #optional
      - HOST_WHITELIST= #optional
    volumes:
      - ${PATH_TO_CONFIG}:/config
      - ${PATH_TO_DOWNLOADS}:/downloads #optional
      - ${PATH_TO_WATCH_FOLDER}:/watch #optional
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped
