services:
  bookstack:
    image: lscr.io/linuxserver/bookstack
    container_name: bookstack
    environment:
      - PUID=1000
      - PGID=1000
      - APP_URL=${APP_URL}
      - DB_HOST=bookstack_db
      - DB_PORT=3306
      - DB_USER=bookstack
      - DB_PASS=${DB_USER_PASS}
      - DB_DATABASE=bookstackapp
    volumes:
      - ${PATH_TO_CONFIG}:/config
    ports:
      - 6875:80
    restart: unless-stopped
    depends_on:
      - bookstack_database
 
  bookstack_database:
    image: lscr.io/linuxserver/mariadb
    container_name: bookstack_database
    environment:
      - PUID=1000
      - PGID=1000
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASS}
      - TZ=${TZ}
      - MYSQL_DATABASE=bookstackapp
      - MYSQL_USER=bookstack
      - MYSQL_PASSWORD=${DB_USER_PASS}
    volumes:
      - ${PATH_TO_DB}:/config
    restart: unless-stopped