services:
  app:
    image: jc21/nginx-proxy-manager:latest
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - 80:80
      - 81:81
      - 443:443
    volumes:
      - ${NGINX_DATA}:/data
      - ${NGINX_LETSENCRYPT}:/etc/letsencrypt