version: '2'
services:
  cloudflare-ddns:
    container_name: ddns-cloudflare
    image: oznu/cloudflare-ddns:latest
    restart: always
    environment:
      - API_KEY=26bgX1izUPGNhPyGJ_6RV9fR_Dk9iwhuUgEoWk5Z
      - ZONE=xopek.co.uk
      - PROXIED=true
      - PUID=1000
      - PGID=1000