version: '3.3'
services:
 nextcloud:
    image: lscr.io/linuxserver/nextcloud:latest
    container_name: nextcloud
    environment:
      - PUID=1000
      - PGID=1000
      - PHP_MEMORY_LIMIT=2048M
      - PHP_UPLOAD_LIMIT=5120M
      - TZ=Europe/Warsaw

    volumes:
      - /home/mbuz/docker/nextcloud/config:/config
      - /mnt/nextcloud_data:/data
    ports:
      - 5443:443
    restart: unless-stopped
    links:
      - nextcloud-mariadb
    depends_on:
      - nextcloud-mariadb
    
 nextcloud-mariadb:
    image: lscr.io/linuxserver/mariadb:latest
    container_name: nextloud-mariadb
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Warsaw
      - MYSQL_ROOT_PASSWORD=Str0ngPa$$1959
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=Jnrhjqcz123

    volumes:
      - /home/mbuz/docker/nextcloud-mariadb:/config
    ports:
      - 5306:3306
    restart: unless-stopped

    
networks:
  default:
    name: nextcloud
    driver: bridge