version: '3.8'
services:
  app:
    image: jc21/nginx-proxy-manager:latest
    restart: unless-stopped
    ports:
      - 1080:80
      - 1081:81
      - 10443:443
    volumes:
      - /home/mbuz/docker/nginx-proxy/data:/data
      - /home/mbuz/docker/nginx-proxy/letsencrypt:/etc/letsencrypt