version: "3.7"

services:
  mealie-frontend:
    image: hkotel/mealie:frontend-v1.0.0beta-5
    container_name: mealie-frontend
    env_file:
      - stack.env
    environment:
    # Set Frontend ENV Variables Here
      - API_URL=http://mealie-api:9000
    restart: unless-stopped
    ports:
      - "9925:3000"
    volumes:
      - ${DATA_FOLDER}/mealie:/app/data/
  mealie-api:
    image: hkotel/mealie:api-v1.0.0beta-5
    container_name: mealie-api
    deploy:
      resources:
        limits:
          memory: 1024M
    volumes:
      - ${DATA_FOLDER}/mealie:/app/data/
    environment:
    # Set Backend ENV Variables Here
      - ALLOW_SIGNUP=true
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Warsaw
      - MAX_WORKERS=1
      - WEB_CONCURRENCY=1
      - BASE_URL=${BASE_URL}
    restart: unless-stopped

volumes:
  mealie-data:
    driver: local