version: "2.1"
services:
  webtop:
    image: lscr.io/linuxserver/webtop:debian-mate
    container_name: webtop
    env_file:
      - stack.env     
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Warsaw
#      - CUSTOM_USER=user
#      - PASSWORD=password
    volumes:
      - /home/mbuz/docker/webtop:/config
    ports:
      - 3000:3000
    devices:
      - /dev/dri:/dev/dri #optional
    shm_size: "2gb" #optional
    restart: unless-stopped