# An image from abesnier that works as an all-in-one and does not require database initiation. 
# I don't know if it has any limitations. For my needs it fits perfectly. 

services:
  guacamole:
    image: abesnier/guacamole:latest
    container_name: guacamole
    volumes:
      - ${PATH_TO_CONFIG}:/config
    ports:
      - 8080:8080
